import json

# IMPORTANT: Run this on the NEW profile generated by the
# entity-centric code I provided, NOT the old 12,000-line one.
PROFILE_PATH = "TUBETL_DATA/6O2T/6O2T.json"

try:
    with open(PROFILE_PATH, 'r') as f:
        data = json.load(f)
except FileNotFoundError:
    print(f"Error: Profile not found at {PROFILE_PATH}")
    print("Please run the new etl/collector.py first.")
    exit()


proteins = data.get('proteins', [])
other_polymers = data.get('other_polymers', [])

all_polymers = proteins + other_polymers

print(f"--- Verification Report for {data.get('rcsb_id')} ---")

print(f"\nFound {len(proteins)} Tubulin Protein Entities:")
for p in proteins:
    print(f"  - Entity {p['entity_id']} ({p['family']}): {p['rcsb_pdbx_description'][:40]}... ({len(p['auth_asym_ids'])} instances)")

print(f"\nFound {len(other_polymers)} Other Polymer Entities:")
for p in other_polymers:
    print(f"  - Entity {p['entity_id']} ({p['entity_poly_polymer_type']}): {p['rcsb_pdbx_description'][:40]}... ({len(p['auth_asym_ids'])} instances)")

print("\n-------------------------------------------------")
print(f"Total Unique Polymer Entities found: {len(all_polymers)}")
print("This number should match the highest entity_id you see in the assembly map.")
